import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  container: {
    display: "flex",
    alignItems: "center",
    flex: 1,
    backgroundColor: "#FFFFF",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },

  forms: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 10,
  },
  input: {
    margin: 9,
    borderWidth: 1,
    minWidth: Dimensions.get("window").width * 0.25,
    maxWidth: Dimensions.get("window").width * 0.25,
    borderColor: "#CCCCCC",
    padding: 10,
    fontSize: 18,
    overflow: "scroll",
  },

  inputField: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  buttons: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 4,
    elevation: 3,
    fontSize: 24,
    color: "#FFFFFF",
    backgroundColor: "#F78D6C",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  denCard: {
    backgroundColor: "#f9f4f4",
    padding: 10,
    marginVertical: 12,
    borderRadius: 30,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  numCard: {
    padding: 5,
    backgroundColor: "#f9f4f4",
    borderRadius: 5,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    margin: 5,
  },

  subscript: {
    flexDirection: "row",
    alignItems: "flex-start",
  },

  cancel: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 35,
  },

  cancelText: {
    color: "#434A5D",
    fontSize: 20,
  },

  title: {
    display: "flex",
    textAlign: "center",
    flexDirection: "row",
    color: "#434A5D",
    fontSize: 20,
    textTransform: "uppercase",
    margin: 10,
    fontWeight: "bold",
  },
  subtitle: {
    color: "#434A5D",
    fontSize: 17,
    textAlign: "center",
  },
  densityBody: {
    padding: 20,
    paddingTop: 30,
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  lineSeparator: {
    borderWidth: 1,
    borderColor: "#CCCCCC",
    width: 300,
    alignSelf: "center",
    margin: 2,
    backgroundColor: "#CCCCCC",
  },
  row: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },

  column: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  convertSelection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    margin: 20,
    backgroundColor: "#F78D6C",
    borderRadius: 20,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowColor: "#CCCCCC",
    shadowRadius: 2,
  },
  convertLabel: {
    color: "white",
    padding: 20,
    fontWeight: "bold",
  },
  errormsg: {
    color: "tomato",
    fontWeight: "bold",
    padding: 10,
    fontSize: 12,
  },
  emptymsg: {
    height: 0,
  },
  icon: {
    backgroundColor: "#ffa180",
    borderWidth: 3,
    borderColor: "#F78D6C",
    borderRadius: 20,
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    padding: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
});
