import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  container: {
    display: "flex",
    flex: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  containerUncentered: {
    display: "flex",
    flex: 1,
    backgroundColor: "#FFFFFF",
    width: "100%",
  },
  forms: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  input: {
    margin: 9,
    borderWidth: 1,
    minWidth: Dimensions.get("window").width * 0.25,
    maxWidth: Dimensions.get("window").width * 0.25,
    borderColor: "#CCCCCC",
    padding: 10,
    fontSize: 18,
    overflow: "scroll",
  },

  inputField: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  buttons: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 4,
    elevation: 3,
    fontSize: 24,
    color: "#FFFFFF",
    backgroundColor: "#F78D6C",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  denCard: {
    backgroundColor: "#f9f4f4",
    width: Dimensions.get("window").width * 0.9,
    padding: 8,
    borderRadius: 30,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  numCard: {
    padding: 5,
    backgroundColor: "#f9f4f4",
    borderRadius: 5,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    margin: 5,
  },

  subscript: {
    flexDirection: "row",
    alignItems: "flex-start",
  },

  cancel: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 35,
  },

  cancelText: {
    color: "#434A5D",
    fontSize: 20,
  },

  title: {
    display: "flex",
    textAlign: "center",
    flexDirection: "row",
    color: "#434A5D",
    fontSize: 18,
    textTransform: "uppercase",
    margin: 10,
    fontWeight: "bold",
  },
  subtitle: {
    color: "#434A5D",
    fontSize: 17,
    textAlign: "center",
  },
  densityBody: {
    transform: [{ scale: 0.9 }],
    margin: -10,
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  lineSeparator: {
    borderBottomWidth: 1,
    borderColor: "#CCCCCC",
    width: 300,
    alignSelf: "center",
    margin: 2,
    backgroundColor: "#CCCCCC",
  },
  row: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
  },

  column: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  convertSelection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    margin: 20,
    backgroundColor: "#F78D6C",
    borderRadius: 20,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowColor: "#CCCCCC",
    shadowRadius: 2,
  },
  convertLabel: {
    color: "white",
    padding: 20,
    fontWeight: "bold",
  },
  errormsg: {
    color: "tomato",
    fontWeight: "bold",
    fontSize: 11,
  },
  emptymsg: {
    height: 0,
  },
  icon: {
    backgroundColor: "#ffa180",
    borderWidth: 2,
    borderColor: "#F78D6C",
    borderRadius: 20,
    borderBottomRightRadius: 0,
    borderTopRightRadius: 0,
    padding: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  centerScroll: {
    display: "flex",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  inputColumn: {
    display: "flex",
    flexDirection: "column",
    flexWrap: "wrap",
    alignItems: "flex-end",
    backgroundColor: "#f9f4f4",
    width: Dimensions.get("window").width * 0.9,
    padding: 8,
    margin: "5%",
    borderRadius: 30,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  presetContainer: {
    flex: 1,
    display: "flex",
    alignItems: "center",
  },
  PresetCard: {
    width: "80%",
    alignSelf: "center",
    backgroundColor: "#f9f4f4",
    borderRadius: 5,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    margin: "4%",
    padding: 4,
    flexDirection: "row",
    alignItems: "space-between",
    justifyContent: "space-between",
  },
  presetTitle: {
    maxWidth: "80%",
    fontSize: 14,
    color: "#434A5D",
    fontWeight: "500",
  },
  presetList: { width: "100%", flex: 1, minHeight: "100%", paddingTop: "10%" },
  popUpNotify: {
    width: "90%",
    height: "60%",
    borderColor: "#ccc",
    borderWidth: 1,
    borderStyle: "solid",
    backgroundColor: "white",
    elevation: 20,
    padding: 10,
    borderRadius: 4,
  },
  historyCardGrid: {
    paddingVertical: "5%",
    paddingHorizontal: 2,
    width: "48%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "#fafafa",
  },
  gridItem: {
    width: "50%",
    color: "#434A5D",
    fontSize: 10,
  },
  historyCard: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    width: Dimensions.get("window").width * 1,
  },
  shareDataForm: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "100%",
    width: "100%",
  },

  dataViewContainer: {
    minHeight: Dimensions.get("window").height * 0.5,
    width: Dimensions.get("window").width * 0.9,
    borderRadius: 10,
    margin: 10,
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
});
